{
 "title": "Application Service Details",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Application Service",
    "query": {}
   },
   {
    "name": "ci",
    "query": {}
   },
   {
    "name": "allMetrics",
    "label": "Available Metrics",
    "query": {}
   },
   { "name": "childTopo", "label": "Child Topo Levels", "query": "0,1,2,3,4,5" },
   { "name": "parentTopo", "label": "Parent Topo Levels", "query": "0,1,2,3,4,5" },
   {
    "name": "filterClasses",
    "query": {}
   },
   { "name": "namespaces" },
   {
    "name": "nestedCIS",
    "query": {}
   },
   { "name": "dependsOnFilter", "query": "On : true, Off : false" }
  ]
 },
 "panels": [
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "sysparam_option1": [
      { "description": "sys_id", "label": "Sys ID", "value": "sys_id" }
     ],
     "sysparam_option2": [
      { "label": "is", "value": "=" }
     ],
     "sysparam_option3": [
      { "label": "$service", "value": "$service" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "tableName": { "description": "cmdb_ci_service_discovered", "label": "Mapped Application Service", "value": "cmdb_ci_service_discovered" }
    }
   ]
  },
  {
   "title": "Service Availability",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "selectedQueryCategory": {
      "description": "Gathers business service status over the last 90 days",
      "label": "Outage Status",
      "value": "Outage_Status"
     },
     "selectedServiceList": { "label": "$service", "value": "$service" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  { "title": "Topology", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "novatec-sdg-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Topology", "label": "Topology", "value": "Topology" },
     "selectedServiceList": {
      "__isNew__": true,
      "label": "$service",
      "value": "$service"
     },
     "selectedTopologyDependsOnFilter": { "label": "$dependsOnFilter", "value": "$dependsOnFilter" },
     "service": "$service",
     "topology_child_depth": "$childTopo",
     "topology_depth": 3,
     "topology_filter": "$filterClasses",
     "topology_namespaces": "$namespaces",
     "topology_parent_depth": "$parentTopo"
    }
   ]
  },
  {
   "title": "Overall Noise Reduction Last 30 Days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "event_count",
     "depends_on_toggle": "$dependsOnFilter",
     "groupBy": "state",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedAggregateType": { "label": "SUM", "value": "SUM" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "service": "$service",
     "source": "$source",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ci.sys_idIN$nestedCIS",
     "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
    },
    {
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "service": "$service",
     "source": "$source",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^group_source!=5^cmdb_ci.sys_idIN$nestedCIS",
     "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "Incidents Last 30 Days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "service": "$service",
     "source": "$source",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ci.sys_idIN$nestedCIS",
     "tableName": { "label": "Incident (incident)", "value": "incident" }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "selectedQueryCategory": {
      "description": "Get timeseries data based on a time trend",
      "label": "Trend Data",
      "value": "Trend_Data"
     },
     "selectedTrendBy": { "label": "Minute", "value": "minute" },
     "selectedTrendColumn": { "label": "Created", "value": "sys_created_on" },
     "sysparam_option1": [
      null
     ],
     "sysparam_option2": [
      null
     ],
     "sysparam_option3": [
      null
     ],
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" },
     "trendPeriod": "1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 21 },
   "options": {
    "content": "❗If the topology panel is returning an error or loading for a long time, you may be requesting too much data at once. <br/> Try adding more classes to the exclude list or lower your parent/child search levels to refine the search\n           "
   },
   "targets": [
    {
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$source"
    }
   ]
  },
  {
   "title": "Cloud Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sysparam_option1": [
        { "description": "ci.sys_id", "label": "Configuration Item => Sys ID", "value": "ci.sys_id" }
       ],
       "sysparam_option2": [
        { "label": "is one of", "value": "IN" }
       ],
       "sysparam_option3": [
        { "label": "$nestedCIS", "value": "$nestedCIS" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "sn_cmp_cloud_event", "label": "Cloud Event", "value": "sn_cmp_cloud_event" }
      }
     ]
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Alerts",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
       "selectedAlertTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
       "service": "$service",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ci.sys_idIN$nestedCIS"
      }
     ]
    }
   ]
  },
  {
   "title": "All Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "$allMetrics",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "repeat": "allMetrics",
     "targets": [
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricAnomaly": "false",
       "metricName": "$allMetrics",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": { "label": "$allMetrics", "value": "$allMetrics" },
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedSourceList": [
        { "label": "$nestedCIS", "value": "$nestedCIS" }
       ],
       "service": "$service",
       "source": "$nestedCIS",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Recent Change Records",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedChangeTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Changes", "label": "Changes", "value": "Changes" },
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ciIN$nestedCIS"
      }
     ]
    }
   ]
  },
  {
   "title": "Checks Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics Table",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "metricAnomaly": "false",
       "metricName": "*",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "*", "value": "*" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$service", "value": "$service" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  }
 ]
}