{
 "title": "CI Details",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ciClasses",
    "query": {}
   },
   {
    "name": "ci",
    "query": {}
   },
   {
    "name": "metric",
    "label": "Metric KPI",
    "query": {}
   },
   {
    "name": "allMetrics",
    "label": "All Metrics",
    "query": {}
   },
   { "name": "childTopo", "label": "Child Topo Levels", "query": "0,1,2,3,4,5" },
   { "name": "parentTopo", "label": "Parent Topo Levels", "query": "0,1,2,3,4,5" },
   {
    "name": "filterClasses",
    "label": "Exclude Classes",
    "query": {}
   },
   { "name": "namespaces" },
   {
    "name": "nestedCIS",
    "query": {}
   },
   {
    "name": "metric_type",
    "query": {}
   },
   { "name": "dependsOn", "query": "On : true, Off : false" }
  ]
 },
 "panels": [
  { "title": "$ci", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "metricName": "/cpu|memory/",
     "metricType": "*",
     "selectedAgentFilter": {
      "__isNew__": true,
      "label": "$ci",
      "value": "$ci"
     },
     "selectedAgentFilterType": { "description": "Get all agents matching the CI", "label": "CI", "value": "CI" },
     "selectedMetricNameList": [
      {
       "__isNew__": true,
       "label": "cpu",
       "value": "cpu"
      },
      {
       "__isNew__": true,
       "label": "memory",
       "value": "memory"
      }
     ],
     "selectedMetricTypeList": [
      { "label": "*", "value": "*" }
     ],
     "selectedQueryCategory": { "description": "Get Agent information", "label": "Agents", "value": "Agents" },
     "service": "$service",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  { "title": "Topology", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "novatec-sdg-panel",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Topology", "label": "Topology", "value": "Topology" },
     "selectedServiceList": {
      "__isNew__": true,
      "label": "$ci",
      "value": "$ci"
     },
     "selectedTopologyDependsOnFilter": { "label": "$dependsOn", "value": "$dependsOn" },
     "service": "$service",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "topology_child_depth": "$childTopo",
     "topology_depth": 3,
     "topology_filter": "$filterClasses",
     "topology_parent_depth": "$parentTopo"
    }
   ]
  },
  {
   "title": "$metric",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 5 },
   "repeat": "metric",
   "targets": [
    {
     "metricAnomaly": "true",
     "metricName": "$metric",
     "metricType": "*",
     "selectedMetricAnomalyList": { "description": "", "label": "true", "value": "true" },
     "selectedMetricNameList": { "label": "$metric", "value": "$metric" },
     "selectedMetricTypeList": [
      { "label": "*", "value": "*" }
     ],
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "selectedServiceList": { "label": "ServiceNow Event Management", "value": "ServiceNow Event Management" },
     "selectedSourceList": [
      { "label": "$ci", "value": "$ci" }
     ],
     "service": "$service",
     "source": "$ci",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 21 },
   "options": {
    "content": "❗If the topology panel is returning an error or loading for a long time, you may be requesting too much data at once. <br/> Try adding more classes to the exclude list or lower your parent/child search levels to refine the search\n           "
   },
   "targets": [
    {
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$source"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall Noise Reduction Last 30 Days",
     "type": "stat",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregateColumn": "event_count",
       "depends_on_toggle": "$dependsOnFilter",
       "groupBy": "state",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedAggregateType": { "label": "SUM", "value": "SUM" },
       "selectedQueryCategory": {
        "description": "Group by and apply aggregate functions to table data",
        "label": "Aggregate",
        "value": "Aggregate"
       },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ci.sys_idIN$nestedCIS^state!=Closed",
       "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
      },
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^group_source!=5^cmdb_ci.sys_idIN$nestedCIS^state!=Closed",
       "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
      }
     ]
    },
    {
     "title": "Incidents Last 30 Days",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ci.sys_idIN$nestedCIS",
       "tableName": { "label": "Incident (incident)", "value": "incident" }
      }
     ]
    },
    {
     "title": "Active Alerts",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
       "selectedAlertTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
       "service": "$service",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ci.sys_idIN$nestedCIS"
      }
     ]
    }
   ]
  },
  {
   "title": "Cloud Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sysparam_option1": [
        { "description": "ci.sys_id", "label": "Configuration Item => Sys ID", "value": "ci.sys_id" }
       ],
       "sysparam_option2": [
        { "label": "is one of", "value": "IN" }
       ],
       "sysparam_option3": [
        { "label": "$nestedCIS", "value": "$nestedCIS" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "sn_cmp_cloud_event", "label": "Cloud Event", "value": "sn_cmp_cloud_event" }
      }
     ]
    }
   ]
  },
  {
   "title": "All Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "$allMetrics",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "repeat": "allMetrics",
     "targets": [
      {
       "metricAnomaly": "false",
       "metricName": "$allMetrics",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": { "label": "$allMetrics", "value": "$allMetrics" },
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Change Records",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedChangeTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Changes", "label": "Changes", "value": "Changes" },
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ciIN$nestedCIS"
      }
     ]
    }
   ]
  },
  {
   "title": "Checks Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics Table",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "metricAnomaly": "false",
       "metricName": "*",
       "metricType": "*",
       "selectedMetricAnomalyList": { "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "*", "value": "*" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  }
 ]
}