apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  labels:
    app: adservice
    version: v1.0
    busapp: boutique
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
        version: v1.0
        busapp: boutique
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        #image: pangealab/adservice:latest
        image: demowow/adservice:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9555
        envFrom:
        - configMapRef:
            name: lightstep-configmap
        env:
        - name: PORT
          value: "9555"
        - name: LS_SERVICE_NAME
          value: adservice
        - name: LS_SERVICE_VERSION
          value: v1.0
        - name: LS_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: lightstep-credentials
              key: accessToken
        # - name: DISABLE_STATS
        #   value: "1"
        # - name: DISABLE_TRACING
        #   value: "1"
        # - name: JAEGER_SERVICE_ADDR
        #  value: "simplest-collector.jaeger.svc.cluster.local:14268"
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
        readinessProbe:
          failureThreshold: 30
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]
        livenessProbe:
          failureThreshold: 30
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  labels:
    app: adservice
    version: v1
    busapp: boutique
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
  - name: grpc
    port: 9555
    targetPort: 9555
