apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  labels:
    app: cartservice
    version: v1.0
    busapp: boutique
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
        version: v1.0
        busapp: boutique
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: demowow/cartservice:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7070
        envFrom:
        - configMapRef:
            name: lightstep-configmap
        env:
        - name: REDIS_ADDR
          value: "redis-cart:6379"
        - name: LS_SERVICE_NAME
          value: cartservice
        - name: LS_SERVICE_VERSION
          value: v1.0
        - name: LS_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: lightstep-credentials
              key: accessToken
        # - name: DISABLE_STATS
        #   value: "1"
        # - name: DISABLE_TRACING
        #   value: "1"
        # - name: DISABLE_PROFILER
        #   value: "1"
        #- name: JAEGER_SERVICE_ADDR
        #  value: "simplest-collector.jaeger.svc.cluster.local:14268"
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
        readinessProbe:
          failureThreshold: 30
          #initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
        livenessProbe:
          failureThreshold: 30
          #initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  labels:
    app: cartservice
    version: v1
    busapp: boutique
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
  - name: grpc
    port: 7070
    targetPort: 7070
