# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  labels:
    app: checkoutservice
    version: v1.0
    busapp: boutique
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
        version: v1.0
        busapp: boutique
    spec:
      serviceAccountName: default
      containers:
        - name: server
          #image: pangealab/checkoutservice:latest
          image: demowow/checkoutservice:v1.0 
          ports:
          - containerPort: 5050
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 15
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 15
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          envFrom:
          - configMapRef:
              name: lightstep-configmap              
          env:
          - name: PORT
            value: "5050"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice:3550"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice:50051"
          - name: PAYMENT_SERVICE_ADDR
            value: "paymentservice:50051"
          - name: EMAIL_SERVICE_ADDR
            value: "emailservice:5000"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice:7000"
          - name: CART_SERVICE_ADDR
            value: "cartservice:7070"
          - name: LS_SERVICE_NAME
            value: checkoutservice
          - name: LS_SERVICE_VERSION
            value: v1.0
          - name: LS_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: lightstep-credentials
                key: accessToken            
          # - name: DISABLE_STATS
          #   value: "1"
          # - name: DISABLE_TRACING
          #   value: "1"
          # - name: DISABLE_PROFILER
          #   value: "1"
          - name: JAEGER_SERVICE_ADDR
            value: "simplest-collector.jaeger.svc.cluster.local:14268"
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
  - name: grpc
    port: 5050
    targetPort: 5050
