apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  labels:
    app: currencyservice
    version: v1.0
    busapp: boutique
spec:
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
        version: v1.0
        busapp: boutique
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        #image: pangealab/currencyservice:latest
        image: demowow/currencyservice:v1.0 
        ports:
        - name: grpc
          containerPort: 7000
        envFrom:
        - configMapRef:
            name: lightstep-configmap
        env:
        - name: PORT
          value: "7000"
        # Lightstep config
        # - name: OTEL_LOG_LEVEL
        #  value: DEBUG          
        - name: LS_SERVICE_NAME
          value: currencyservice
        - name: LS_SERVICE_VERSION
          value: v1.0
        - name: LS_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: lightstep-credentials
              key: accessToken
       #- name: JAEGER_SERVICE_ADDR
       #  value: "simplest-collector.jaeger.svc.cluster.local:14268"
        readinessProbe:
          failureThreshold: 30
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7000"]
        livenessProbe:
          failureThreshold: 30
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7000"]
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  labels:
    app: currencyservice
    version: v1
    busapp: boutique
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
  - name: grpc
    port: 7000
    targetPort: 7000
